### ISSUE TITLE
Re-package as deployable project

### ISSUE THREAD

**Issue by andrewbates09** [WSU-ACM/hackathon-site#1]
Consider using jekyll or similar static website generator to easily make changes to the github and build changes on all pages.

Can start from scratch or grab a jekyll theme and alter it to suit the needs of the website users & developers.

http://jekyllbootstrap.com/
http://jekyllrb.com/

ex:
http://mmistakes.github.io/hpstr-jekyll-theme/
http://mmistakes.github.io/so-simple-theme/
http://dbtek.github.io/dbyll/

Takes some setup, but save so much time throughout the continuity/management process.

**Comment by dylanPowers** [comment]
Pretty much completed
