### ISSUE TITLE
Possible project ideas page

### ISSUE THREAD

**Issue by whyrusleeping** [WSU-ACM/hackathon-site#19]
It would be really nice to have a page where students who don't know what to make could go for ideas.

Feature summary:
* Random idea generator like at http://www.winahackathon.com/
* List of past projects especially the winning ones

**Comment by techfreek** [comment]
Where should the link for the ideas page go? I am thinking either in the the FAQ or the the header. Thoughts?

**Comment by whyrusleeping** [comment]
in the header next to the other links?

**Comment by techfreek** [comment]
Closed in #35
