### ISSUE TITLE
Add gallery functionality to pictures for better experience

### ISSUE THREAD

**Issue by andrewbates09** [WSU-ACM/hackathon-site#2]
This was in the works and a simple way to add a good looking gallery would be to package the fancyBox tool in with the website.  The idea would be to keep the polaroid layout, however when clicked it opens up a gallery at that position.

http://fancyapps.com/fancybox/#examples

Consider the "Thumbnail Helper" under "Extended Functionality."  It is sleek and easy to package up and add.

**Comment by techfreek** [comment]
Implemented in f0fa2ddff349b65b217497ff865c73ea57ac24c9
