### ISSUE TITLE
Logos for companies

### ISSUE THREAD

**Issue by travisperson** [WSU-ACM/hackathon-site#32]
I can provide you with all the actual logos as long as you can find a nice place to put them.

**Comment by dylanPowers** [comment]
I have all the logos covered except for maybe the smaller companies. I haven't looked too deeply. As we find them we should place them in https://drive.google.com/drive/#folders/0B90pmClorJFlZmFfc0tmc2Jndm8/0B6wWauUjG47Dd0QtcmpRMHJmMU0/0B_5ocdd5sbb5VmpweWJZSlI2X3M for easy retrieval.

**Comment by dylanPowers** [comment]
I noticed Natasha put the HP ones in there already. I would prefer to get png's that are ready to go, but then again with multiple sizes it's hard to figure out beforehand what resolution we'll need.

**Comment by dylanPowers** [comment]
This is technically a duplicate of #12 so I'm closing this.
