### ISSUE TITLE
Clicking on an image results in a 404

### ISSUE THREAD

**Issue by techfreek** [WSU-ACM/hackathon-site#34]
Example in this image:
```
<a href="http://hackathon.eecs.wsu.edu/images/hackathon_02/IMG_1162.jpg" target="_blank">
<img src="http://hackathon.eecs.wsu.edu/images/hackathon_02_mini/IMG_1162.jpg">
</a>
```

http://hackathon.eecs.wsu.edu/images/hackathon_02_mini/IMG_1162.jpg works fine
http://hackathon.eecs.wsu.edu/images/hackathon_02/IMG_1162.jpg -> 404

**Comment by dylanPowers** [comment]
You somehow have an old version of the website. The urls have changed.

**Comment by techfreek** [comment]
Alright. I'll close this, but maybe we set the cache expiration date to be shorter?
