### ISSUE TITLE
Node server memory leak

### ISSUE THREAD

**Issue by techfreek** [WSU-ACM/hackathon-site#38]
The node server uses a ton of memory. In 24 hours it ballooned to >200mb.

Thoughts on the cause:
* Memory leak
* The eventbrite API sends a ton of data. We should only use the fields we need and throw away the rest

**Comment by dylanPowers** [comment]
Not a memory leak. Just node being bloated. The server has plenty of memory so we're good to go on this.

**Comment by whyrusleeping** [comment]
Man, sounds like we could use some Go.

**Comment by t-walker** [comment]
Go hard or Go home.

**Comment by techfreek** [comment]
Maybe I should try to make it in Go for giggles
