### ISSUE TITLE
Last minute stuff

### ISSUE THREAD

**Issue by dylanPowers** [WSU-ACM/hackathon-site#39]
https://docs.google.com/document/d/14J0Nc2IKlXL14InbEOKsUU3FE6eiypuOs-CDpaOaiQc/edit

**Comment by techfreek** [comment]
Should we create a day of page for this?

**Comment by dylanPowers** [comment]
I'll tell you what, this website has been steadily rising in complexity to the point that it's too big for the current design. I like the idea of entirely gutting the front page and turning it into a "day of page"

**Comment by techfreek** [comment]
I'm okay with re-designing things. For now, turning the front page into a day of page (keeping the sponsors there though) work for me. If we re-do how the build system works or anything like that, that can come after the hackathon

**Comment by techfreek** [comment]
@dylanPowers, are you able to create the day of page for the hackathon?

**Comment by dylanPowers** [comment]
The only hope I have is to create it at the hackathon which is unfortunate

**Comment by techfreek** [comment]
I don't have time to work on it, so creating it day of will have to suffice

**Comment by dylanPowers** [comment]
It never happened and IDGAF
