### ISSUE TITLE
Site is down.

### ISSUE THREAD

**Issue by andrewbates09** [WSU-ACM/hackathon-site#45]
Dunno if you're aware, but the site is down.

**Comment by techfreek** [comment]
We are aware, we haven't had a chance to fix this just yet.

**Comment by andrewbates09** [comment]
Wasn't sure, it'd been a week/few since I last saw it up. Hosting or code issue?

**Comment by dylanPowers** [comment]
WSU IT fucked us and broke the CSG's internet connection. We had to change IP addresses and piggyback off somebody else (I forget who. @whyrusleeping knows) to get at least the internet working. The DNS however hasn't been updated for the new IP. I have no idea what sort of bureaucracy we have to go through to get that sorted out.

**Comment by t-walker** [comment]
E-mail APG and have him update the DNS records.

**Comment by t-walker** [comment]
apg@eecs.wsu.edu or go up to the EECS help desk

**Comment by dylanPowers** [comment]
@t-walker Any idea if the current configuration is stable? To me it sounded like a short term hack

**Comment by t-walker** [comment]
No clue.

**Comment by whyrusleeping** [comment]
its more stable than it was. now we just rely on apg instead of wsu IT to fuck us as they please.

**Comment by t-walker** [comment]
@dylanPowers can take charge of restoring the connection?

**Comment by apg007** [comment]
So... what's it suppose to be?
apg@bent ~ # dig hackathon.eecs.wsu.edu any

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.30.rc1.el6_6.3 <<>> hackathon.eecs.wsu.edu any
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24709
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 2

;; QUESTION SECTION:
;hackathon.eecs.wsu.edu.                IN      ANY

;; ANSWER SECTION:
hackathon.eecs.wsu.edu. 21600   IN      CNAME   csg-gate.eecs.wsu.edu.

**Comment by whyrusleeping** [comment]
@apg007 I think this is something wrong with the apache/iptables config on csg-gate. the hackathon.eecs.wsu.edu dns records look fine

**Comment by dylanPowers** [comment]
@whyrusleeping must be iptables then...At least csg-gate.eecs.wsu.edu is working. Sorry for bothering you @apg007 
@t-walker is working on getting us moved over to digital ocean

**Comment by apg007** [comment]
YOU are the provider, regardless of the host. The cloud is not a silver bullet. It appears, at first blush, that your httpd (apache?) is not running:
nmap 134.121.64.116

Starting Nmap 5.51 ( http://nmap.org ) at 2015-06-10 13:12 PDT
Nmap scan report for csg-gate.eecs.wsu.edu (134.121.64.116)
Host is up (0.00071s latency).
Not shown: 996 closed ports
PORT     STATE SERVICE
53/tcp   open  domain
111/tcp  open  rpcbind
2020/tcp open  xinupageserver
4001/tcp open  newoak
MAC Address: 00:14:22:20:32:8B (Dell)

Nmap done: 1 IP address (1 host up) scanned in 1.28 seconds

**Comment by dylanPowers** [comment]
@apg007 you hit the gateway. Ports are suppose to be forwarded to the servers that are running on the CSG's internal network...or something like that. I never actually worked on the networking for the CSG.
@t-walker @whyrusleeping How did the firewall get so misconfigured? Did it happen while trying to work around the original blockade?

**Comment by apg007** [comment]
ah, yes, of course. NATing can be a bit tricky.

**Comment by whyrusleeping** [comment]
Yeah, its just crappy NATing issues...

**Comment by t-walker** [comment]
Crappy NATing issues have been resolved.

**Comment by andrewbates09** [comment]
:+1:

**Comment by apg007** [comment]
As per Dylan Powers request, I just changed hackathon.eecs.wsu.edu A record to 45.55.243.93

**Comment by t-walker** [comment]
Thanks APG!
