### ISSUE TITLE
Migrate to cloud provider

### ISSUE THREAD

**Issue by dylanPowers** [WSU-ACM/hackathon-site#46]
The ACM/CSG networking is fragile as evidenced by https://github.com/WSU-ACM/hackathon-site/issues/45. Plus we do a lot of tinkering on that network. We need something more stable. @t-walker mentioned hosting on digital ocean. Should probably exhaust our eecs options first. Further discussion at https://github.eecs.wsu.edu/ACM/administration/issues/4

**Comment by dylanPowers** [comment]
On digital ocean now

**Comment by t-walker** [comment]
Perfection.
