### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by dylanPowers** [WSU-ACM/hackathon-site#48]
I've been doing some research into Docker. There's a lot of hype and I've been trying to cut through the hype to figure out how it can benefit us. What I'm seeing is that by "containerizing" the site we should be able to simplify development setup and not have such a difference between dev and production environments. For instance dev has a Node.js implemented proxy server while production uses nginx. It should turn a first time dev environment initialization into a single step rather than what we [currently have](https://github.com/WSU-ACM/hackathon-site/wiki/build-instructions#long-story). Development should also be trivial to do from other unixy systems like OS X. 

Using https://github.com/docker/compose will be critical.

**Comment by dylanPowers** [comment]
I'm still not sure how to handle Jekyll. Production serves through nginx while dev serves through Jekyll. The benefit there is that Jekyll can autowatch for file changes and regenerate sources automatically. I wonder if it's possible to use the autobuilding without the server part?

**Comment by dylanPowers** [comment]
Problem:
Docker requires a lot of really new kernel features. ChromeOS doesn't use the latest greatest Linux kernel. Docker doesn't work in crouton. Docker doesn't work on Chromebooks. We can't use Docker until someone buys me a better computer :( :-1:

**Comment by t-walker** [comment]
Maybe??



TYLER P. WALKER 
Washington State University 
Research Assistant – WSU CptS 
Computer Security Group – President 
206-940-6756 


----- Original Message -----

**Comment by dylanPowers** [comment]
This is partially complete as of d3d7d4ac12766b20d39e0d0e313b18e8d4e9afb3. I still want to add the api server to docker. For this repo however this can be closed.
